#!/usr/bin/env python3

import os
import sys
import glob
import json
import time
import datetime
from dataclasses import dataclass
from typing import Any
from typing import ClassVar
from typing import TypedDict
from urllib.parse import urlparse

import requests

#####################################################
# Configuration
#####################################################
INDEXERS_PATTERN = os.environ.get("INDEXERS_PATTERN", "v0.1/*.json")
ISSUE_BODY_PATH  = os.environ.get("ISSUE_REPORT",     "issue_report.md")
ISSUE_TITLE_PATH = os.environ.get("ISSUE_TITLE",      "issue_title.txt")
PR_BODY_PATH     = os.environ.get("PR_REPORT",        "pullrequest_report.md")
PR_TITLE_PATH    = os.environ.get("PR_TITLE",         "pullrequest_title.txt")

TIMEOUT, RETRIES = 15, 3
HEADERS = {
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36")
}
ALIVE_BUT_REFUSING = {401, 403, 407, 429, 503} # answered, just won't let the bot through

STATUS_DESC = {
    "live":        "alive",
    "blocked":     "alive (challenge / 403)",
    "moved":       "redirected",
    "missing":     "missing — answering, but the root returned 404/410",
    "down":        "down — repeated 5xx or timeouts (could be temporary)",
    "unreachable": "unreachable — DNS / connection / TLS failure (domain looks gone)",
}

#####################################################
# Types
#####################################################
@dataclass(frozen=True)
class Live:        label: ClassVar[str] = "alive"
@dataclass(frozen=True)
class Blocked:     label: ClassVar[str] = "alive (challenge / 403)"
@dataclass(frozen=True)
class Down:        label: ClassVar[str] = "down (repeated 5xx or timeouts (could be temporary))"
@dataclass(frozen=True)
class Unreachable: label: ClassVar[str] = "unreachable (DNS / connection / TLS failure (domain looks gone))"

@dataclass(frozen=True)
class Missing:
    url: str
    label: ClassVar[str] = "missing, but answering (root returned 404/410)"

@dataclass(frozen=True)
class Moved:
    url: str
    label: ClassVar[str] = "redirected"

UrlResult = Live | Blocked | Missing | Down | Unreachable | Moved
JsonDict = dict[str, Any]

#####################################################
# Helpers
#####################################################
def remove_www_from_url(url: str) -> str:
    h = urlparse(url).netloc.lower()
    return h[4:] if h.startswith("www.") else h

def url_to_string(url: str) -> str:
    p = urlparse(url)
    return f"{p.scheme}://{p.netloc}/"

def write_indexer_specification(path: str, cfg: JsonDict) -> None:
    with open(path, "w") as f:
        json.dump(cfg, f, indent="\t")
        f.write("\n")

#####################################################
# Functions
#####################################################
def test_url(url: str) -> UrlResult:
    for attempt in range(RETRIES):
        try:
            response = requests.get(url, headers=HEADERS, timeout=TIMEOUT, allow_redirects=True)
        except requests.Timeout:
            time.sleep(2 * (attempt + 1)) 
            continue
        except requests.RequestException: # ConnectionError/SSL included
            return Unreachable()

        code = response.status_code
        if code in ALIVE_BUT_REFUSING:
            return Blocked()
        if code in (404, 410) or code >= 400:
            return Missing(response.url)
        if code >= 500:
            time.sleep(2 * (attempt + 1)) 
            continue
        if remove_www_from_url(response.url) != remove_www_from_url(url):
            return Moved(response.url)
        return Live()
    return Down()

#####################################################
# Report
#####################################################
def write_issue_report(problems: list[str]) -> None:
    now: datetime.datetime = datetime.datetime.now(datetime.timezone.utc)

    lines: list[str] = [
        "# Indexer health check", 
        "",
        f"_Generated {now:%Y-%m-%d %H:%M UTC}_", 
        "",
        "## Overview",
        "Redirects and working-mirror swaps are handled automatically via PR.",
        "The indexers below could **not** be fixed safely and need a human.", 
        "",
        "## Issues",
    ]

    for problem in problems:
        lines.append(f"- {problem}")

    lines = lines + [
        "",
        "## Disclaimer",
        "This issue is generated by a bot and may contain mistakes."
    ]
    
    with open(ISSUE_BODY_PATH, "w") as f:
        f.write("\n".join(lines))

def write_pr_report(fixes: list[str]) -> None:
    now: datetime.datetime = datetime.datetime.now(datetime.timezone.utc)
    
    lines: list[str] = [
        "# Indexer fixes", 
        "",
        f"_Generated {now:%Y-%m-%d %H:%M UTC}_", 
        "",
        "## Overview",
        f"Automatically fixed {len(fixes)} indexer issues.",
        "The fixes are listed below:",
        "",
        "## Fixes",
    ]

    for fix in fixes:
        lines.append(f"- {fix}")

    lines = lines + [
        "",
        "## Disclaimer",
        "This pull request is generated by a bot and may contain mistakes."
    ]
    
    with open(PR_BODY_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

#####################################################
# Main
#####################################################
def main() -> None:
    problems: list[str] = []
    fixes: list[str] = []

    # Test all indexers
    for indexer_path in sorted(glob.glob(INDEXERS_PATTERN)):
        with open(indexer_path) as file:
            json_body: JsonDict = json.load(file)

        name: str = json_body.get("name", indexer_path)
        urls: list[str] = [json_body.get("url", "")] + [mirror for mirror in json_body.get("mirrors", [])]

        indexer_problems: list[str] = []
        indexer_fixes: list[str] = []

        # Test all urls
        changed = False
        for i, url in enumerate(urls):
            match test_url(url):
                case Live() | Blocked():
                    continue

                case Moved(url=new):
                    old_url: str = url
                    new_url: str = url_to_string(new)

                    urls[i] = new_url
                    
                    indexer_fixes.append(f"**{name}** (`{indexer_path}`): redirected \"{old_url}\" → \"{new_url}\".")
                    changed = True

                case Missing():
                    indexer_problems.append(f"**{name}** (`{indexer_path}`): \"{url}\" is missing (404).")

                case Down():
                    indexer_problems.append(f"**{name}** (`{indexer_path}`): \"{url}\" is (temporarily) down.")

                case Unreachable():
                    if len(urls) != 1:
                        urls.pop(i)
                        changed = True
                        indexer_fixes.append(f"**{name}** (`{indexer_path}`): \"{url}\" is unreachable, removed and swapped by mirror.")
                    else:
                        indexer_fixes = []
                        indexer_problems = [f"**{name}** (`{indexer_path}`): All urls are unreachable."]
                        changed = False

        # If not all are unreachable write to file
        if changed and len(urls) != 0:
            json_body["url"] = urls[0]
            urls.pop(0)
            json_body["mirrors"] = urls
            write_indexer_specification(indexer_path, json_body)

        problems = problems + indexer_problems
        fixes = fixes + indexer_fixes

    for problem in problems:
        print("PROBLEM:", problem)
    for fix in fixes:
        print("FIX:", fix)

    # PR files
    pr_title: str = (f"[Chore] Update {len(fixes)} indexer domain{'s.' if len(fixes) != 1 else '.'}")
    with open(PR_TITLE_PATH, "w") as f:
        f.write(pr_title)

    write_pr_report(fixes)

    # Issue files
    if problems:
        issue_title: str = f"[Issue] {len(problems)} indexer{'s' if len(problems) != 1 else ''} need attention."
        with open(ISSUE_TITLE_PATH, "w") as f:
            f.write(issue_title)

        write_issue_report(problems)

    sys.exit(0)

if __name__ == "__main__":
    main()
